@startuml
skinparam style strictuml
skinparam backgroundcolor transparent
skinparam DefaultTextAlignment center
hide empty description
[*] --> User
User -> Tag :push
Tag -> Release : automatic
@enduml
