package com.ulegalize.international;

import java.util.ListResourceBundle;

/**
 * The type Message fr.
 */
public class Message_fr extends ListResourceBundle {

    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"NATURAL_PERSON", "Personne physique"},
                {"COMPANY", "Personne morale"},
                {"COLLEGUE", "Collègue"},
                {"VIREMENT", "Virement"},
                {"CREDIT", "Carte de crédit"},
                {"CASH", "Espèce"},
                {"BANCONTACT", "Carte de débit"},
                {"CHEQUE", "Chèque"},
                {"NA", "N/A"},
                {"SELL", "Facture vente"},
                {"CREDIT", "Note de crédit"},
                {"TEMP", "Facture temporaire"},
                {"TEMP_NC", "Note de crédit temporaire"},
                {"REMINDER", "Rappel"},
                {"PROVISION", "Provision"},
                {"PRO_ACCOUNT", "Compte professionnel"},
                {"ACCOUNT_TIERS", "Compte tiers / CARPA"},
                {"PERM", "Permanence"},
                {"RECORD", "Tâche enregistrement"},
                {"TASK", "Tâche/Reminder"},
                {"RDV", "Rendez-vous"},
                {"AUD", "Audience"},
                {"CONCLU", "Conclusion"},
                {"OTH", "Autre"},
                {"BA", "BAJ"},
                {"CS", "Conseil"},
                {"DC", "Affaire"},
                {"DF", "Droit collaboratif"},
                {"MEDIATION", "Médiation"},
                {"CONTENTIEUX", "Contentieux"},
                {"FORMATION", "Formation"},
                {"EXPERTISE", "Expertise"},
                {"NEGOCIATION", "Négociation"},
                {"PRECONTENTIEUX", "Précontentieux"},
                {"AVOCAT", "Avocat"},
                {"STAGIAIRE", "Stagiaire"},
                {"ASSISTANT", "Assistant"},
                {"SECRETAIRE_JURIDIQUE", "Secrétaire juridique"},
                {"COLLABORATEUR", "Collaborateur"},
                {"MEDIATEUR", "Médiateur"},
                {"LAWYER_ADVICE_CLIENT", "Avocat conseil client"},
                {"LAWYER_OPPOSING", "Avocat partie adverse"},
                {"LITIGANT_OPPOSING", "Justiciable partie adverse"},
                {"LAWYER_CLIENT", "Avocat client"},
                {"LAWFIRM", "Cabinet"},
                {"LITIGANT_CLIENT", "Justiciable client"},
                {"F", "Madame"},
                {"L", "Mademoiselle"},
                {"M", "Monsieur"},
                {"A", "Maitre"},
                {"D", "Docteur"},
                {"CHANNEL", "Channel"},
                {"M_001", "avec"},
                {"SORTIE", "Sortie"},
                {"ENTREE", "Entrée"},
                {"INVITELITIGANTCONSEIL", "Invitation sur votre dossier"},
                {"INVITECONSEIL", "Invitation à travailler sur un dossier"},
                {"MAILBLANKTEMPLATE", "Partage de votre dossier"},
                {"MAILSIGNDOCUMENT", "Signature du document "},
                {"MAILFINISHSIGNOWNERCLIENTDOCUMENT", "Signature du document "},
                {"MAILFINISHSIGNCLIENTDOCUMENT", "Signature du document "},
                {"MAILATTACHDOCUMENTCASE", "Document attaché "},
                {"MAILATTACHDOCUMENTCASEFROMPORTAL", "Un fichier a été attaché au cas juridique"},
                {"MAILSAVEOWNERCASE", "Changement de la prise en charge pour le cas juridique "},
                {"MAILUPDATEDOCUMENTCASE", "Modification du cas juridique "},
                {"MAILFINISHSIGNDOCUMENT", " Signature du document "},
                {"MAILAPPOINTMENT_ADDED_NOTIFICATION", "Ulegalize: Notification agenda"},
                {"MAILAPPOINTMENT_ADDED_MENTION", "Ulegalize: Notification agenda"},
                {"MAILAPPOINTMENT_UPDATE_TASK_STATUS", "Ulegalize Task: Changement de status"},
                {"MAILAPPOINTMENT_CANCEL_NOTIFICATION", "Ulegalize: Annulation agenda"},
                {"MAILAPPOINTMENTCONFIRMEDTEMPLATE", "Ulegalize: Demande de rendez-vous confirmée"},
                {"MAILAPPOINTMENTREGISTEREDTEMPLATE", "Nouvelle demande de rendez-vous"},
                {"MAILNEWAPPOINTMENTREQUESTTEMPLATE", "Demande de rendez-vous enregistrée"},
                {"MAILSHAREDFOLDERUSERTEMPLATE", "Nouveau partage de dossier "},
                {"MAILSHAREDUSERSECURITYTEMPLATE", "Nouvel acces au cabinet "},
                {"MAILVERIFYTEMPLATE", "Vérifiez votre email utilisateur"},
                {"MAILAUTOMATICREGISTER", "Bienvenue dans votre nouvel espace de travail digital"},
                {"MAILAUTOMATICSUPPORT", "Prise en main & Accompagnement digital"},
                {"MAILAUTOMATICREMINDER", "Rappel accompagnement du Workspace"},
                {"MAILWORKSPACEASSOCIATION", "Demande d'association avec le cabinet"},
                {"MAILPAYMENTCANCELTEMPLATE", "Annulation des modules de paiement"},
                {"MAILPAYMENTFAILURETEMPLATE", "Erreur avec le mode de paiement"},
                {"MAILREPORTKPI", "Report KPI"},
                {"MAILPOSTBID", "Status de votre envoi"},
                {"ADMINISTRATEUR", "Administrateur"},
                {"TIERS_LECTURE", "Tiers - Lecture"},
                {"DOSSIERS_LECTURE", "Dossiers - Lecture"},
                {"COMPTABILITE_LECTURE", "Comptabilité - Lecture"},
                {"ECHEANCIER_LECTURE", "Echéancier - Lecture"},
                {"COMPTABILITE_IMPRESSIONDERAPPORTS", "Comptabilité - Impression de rapports"},
                {"DOSSIERS_VOIRASPECTSFINANCIERS", "Dossiers - Voir aspects financiers"},
                {"DOSSIERS_VOIRNOTEAVOCAT", "Dossiers - Voir note avocat"},
                {"COMPTABILITE_ECRITURE", "Comptabilité - Écriture"},
                {"DOSSIERS_FINANCIER", "Dossiers - Financier"},
                {"TIMESHEET_ECRITURE", "Timesheet - Écriture"},
                {"DOSSIERS_DOCUMENTS", "Dossiers - Documents"},
                {"DOSSIERS_ECRITURE", "Dossiers - Écriture"},
                {"TIERS_ECRITURE", "Tiers - Écriture"},
                {"TABLEAUDEBORD", "Tableau de bord"},
                {"ECHEANCIER_ECRITURE", "Echéancier - Écriture"},
                {"TIMESHEET_LECTURE", "Prestation - Lecture"},
                {"FACTURE_LECTURE", "Facture - Lecture"},
                {"FACTURE_ECRITURE", "Facture - Écriture"},
                {"FACTURE_VALIDATION", "Facture - Validation"},
                {"FACTURE_CONFIGURATION", "Facture - Configuration"},
                {"AVODRIVE_LECTURE", "UDrive - Lecture"},
                {"AVODRIVE_ECRITURE", "UDrive - Ecriture"},
                {"AVODRIVE_PARTAGE", "UDrive - Partage"},
                {"GESTION_DU_COURIER_ENTRANT", "Gestion du courier entrant"},
                {"CALENDAR_LECTURE", "Calendar - Lecture"},
                {"CALENDAR_ECRITURE", "Calendar - Écriture"},
                {"JUSTICIABLE_ECRITURE", "Justiciable - Écriture"},
                {"JUSTICIABLE_ADMIN", "Justiciable - Admin"},
                {"EMAILS_ENVOYER", "Emails - envoyer"},
                {"EMAILS_CONSULTER", "Emails - consulter"},
                {"SUPER_ADMIN", "Super - Admin"},
                // Template
                {"MAILTEMPLATEDOSSIER", "Votre document est prêt à être édité"},
                {"MAILSHARELINKNOTIFICATION", "Un lien de partage pour vous"},
                {"MAILPERSONALREPORT", "Rapport personnel"},
                // EnumDossierContactType
                {"CLIENT", "Client"},
                {"OPPOSING", "Partie adverse"},
                {"PARTY", "Partie"},
                {"OPPONENT_COUNSIL", "Conseil partie adverse"},
                {"OTHER", "Autre"},
                {"OPPOSING_LAWYER", "Avocat partie adverse"},
                {"TRIBUNAL", "Tribunal"},
                {"EXPERT", "Expert"},
                {"NOTARY", "Notaire"},
                {"BAILIFF", "Huissier"},
                {"REPRESENTATIVE", "Mandataire"},
        };
    }

}
