package com.ulegalize.international;

import java.util.ListResourceBundle;

public class Message_nl extends ListResourceBundle {

    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"VIREMENT", "Overschrijving"},
                {"CREDIT", "Kredietkaart"},
                {"CASH", "Contant geld"},
                {"BANCONTACT", "Debetkaart"},
                {"CHEQUE", "Cheque"},
                {"NA", "N/A"},
                {"SELL", "Verkoopfactuur"},
                {"CREDIT", "Creditnota"},
                {"TEMP", "Tijdelijke factuur"},
                {"TEMP_NC", "Creditnota credit"},
                {"PRO_ACCOUNT", "Professioneel account"},
                {"ACCOUNT_TIERS", "Account van derden / CARPA"},
                {"PERM", "Permanent"},
                {"RECORD", "Taak opnemen"},
                {"TASK", "Taak"},
                {"RDV", "Afspraak"},
                {"AUD", "Publiek"},
                {"OTH", "Andere"},
                {"BA", "BAJ"},
                {"DC", "Case"},
                {"DF", "Collaboratief recht"},
                {"MD", "Bemiddeling"},
                {"AVOCAT", "Advocaat"},
                {"STAGIAIRE", "Stagiair"},
                {"ASSISTANT", "Assistent"},
                {"SECRETAIRE_JURIDIQUE", "Gerechtelijk secretaris"},
                {"COLLABORATEUR", "Medewerker"},
                {"MEDIATEUR", "Bemiddelaar"},
                {"LAWYER_ADVICE_CLIENT", "Klantadviseur"},
                {"LAWYER_OPPOSING", "Advocaat van de tegenpartij"},
                {"LITIGANT_OPPOSING", "Gerechtvaardigde tegenpartij"},
                {"LAWYER_CLIENT", "Klant"},
                {"LAWFIRM", "Kantoor"},
                {"LITIGANT_CLIENT", "Klant tegenpartij"},
                {"F", "Mevrouw"},
                {"L", "Juffrouw"},
                {"M", "Mijnheer"},
                {"A", "Mijnheer"},
                {"CHANNEL", "Channel"},
                {"M_001", "met"},
                {"SORTIE", "Uitgang"},
                {"ENTREE", "Ingang"},
                {"INVITELITIGANTCONSEIL", "Uitnodiging om aan een bestand"},
                {"INVITECONSEIL", "Uitnodiging om aan een bestand te werken"},
                {"MAILBLANKTEMPLATE", "Sharing your folder"},
                {"MAILSIGNDOCUMENT", "Document handtekening"},
                {"MAILFINISHSIGNOWNERCLIENTDOCUMENT", "Document handtekening"},
                {"MAILFINISHSIGNCLIENTDOCUMENT", "Document handtekening"},
                {"MAILATTACHDOCUMENTCASE", "Document toegevoegd"},
                {"MAILATTACHDOCUMENTCASEFROMPORTAL", "Er is een dossier bij de rechtszaak gevoegd"},
                {"MAILSAVEOWNERCASE", "Een kabinet toevoegen voor de case"},
                {"MAILUPDATEDOCUMENTCASE", "Wijziging van de rechtszaak"},
                {"MAILFINISHSIGNDOCUMENT", "Documenthandtekening"},
                {"MAILAPPOINTMENT_ADDED_NOTIFICATION", "Ulegalize: Notificatie agenda"},
                {"MAILAPPOINTMENT_CANCEL_NOTIFICATION", "Ulegalize: Cancel agenda"},
                {"MAILAPPOINTMENTCONFIRMEDTEMPLATE", "Ulegalize: Afspraakverzoek bevestigd"},
                {"MAILAPPOINTMENTREGISTEREDTEMPLATE", "Nieuw afspraakverzoek"},
                {"MAILNEWAPPOINTMENTREQUESTTEMPLATE", "Afspraakverzoek geregistreerd"},
                {"MAILSHAREDFOLDERUSERTEMPLATE", "Nieuwe mappen delen "},
                {"MAILSHAREDUSERSECURITYTEMPLATE", "Nieuwe toegang tot de praktijk "},
                {"MAILVERIFYTEMPLATE", "Verifieer uw gebruikers-e-mailadres"},
                {"MAILAUTOMATICREGISTER", "Welkom bij de Ulegalize-werkruimte"},
                {"MAILAUTOMATICSUPPORT", "Begeleiding bij de Workspacee"},
                {"MAILAUTOMATICREMINDER", "Ondersteuning voor herinneringen bij de Workspacee"},
                {"MAILWORKSPACEASSOCIATION", "Verzoek om associatie met het advocatenkantoor"},
                {"MAILPAYMENTCANCELTEMPLATE", "Annulering van betalingsmodules "},
                {"MAILPAYMENTFAILURETEMPLATE", "Fout met betalingsmethode "},
                {"MAILREPORTKPI", "Report KPI "},
                {"MAILPOSTBID", "status van uw zending"},
                {"ADMINISTRATEUR", "Beheerder"},
                {"TIERS_LECTURE", "Tiers - lezen"},
                {"DOSSIERS_LECTURE", "Records - lezen"},
                {"COMPTABILITE_LECTURE", "Accounting - lezen"},
                {"ECHEANCIER_LECTURE", "Schema - lezen"},
                {"COMPTABILITE_IMPRESSIONDERAPPORTS", "Accounting - rapporten afdrukken"},
                {"DOSSIERS_VOIRASPECTSFINANCIERS", "Records - zie financiële aspecten"},
                {"DOSSIERS_VOIRNOTEAVOCAT", "Records - zie opmerking voor advies"},
                {"COMPTABILITE_ECRITURE", "Accounting - schrijven"},
                {"DOSSIERS_FINANCIER", "Records - Financieel"},
                {"TIMESHEET_ECRITURE", "Timesheet - schrijven"},
                {"DOSSIERS_DOCUMENTS", "Records - documenten"},
                {"DOSSIERS_ECRITURE", "Records - schrijven"},
                {"TIERS_ECRITURE", "Tiers - schrijven"},
                {"TABLEAUDEBORD", "Zeiger - schreiben"},
                {"ECHEANCIER_ECRITURE", "Schema - schrijven"},
                {"TIMESHEET_LECTURE", "Prestation - lezen"},
                {"FACTURE_LECTURE", "Factuur - lezen"},
                {"FACTURE_ECRITURE", "Factuur - schrijven"},
                {"FACTURE_VALIDATION", "Factuur - Validatie"},
                {"FACTURE_CONFIGURATION", "Factuur - Configuratie"},
                {"AVODRIVE_LECTURE", "UDrive - lezen"},
                {"AVODRIVE_ECRITURE", "UDrive - schrijven"},
                {"AVODRIVE_PARTAGE", "UDrive - Delen"},
                {"GESTION_DU_COURIER_ENTRANT", "Inkomend koeriersbeheer"},
                {"CALENDAR_LECTURE", "Calendar - lezen"},
                {"CALENDAR_ECRITURE", "Calendar - schrijven"},
                {"JUSTICIABLE_ECRITURE", "Rechtsmiddel - schrijven"},
                {"JUSTICIABLE_ADMIN", "Rechtsmiddel - Admin"},
                {"SUPER_ADMIN", "Super - Admin"},
                // Template
                {"MAILTEMPLATEDOSSIER", "Uw document is klaar om te worden bewerkt"},
                // EnumDossierContactType
                {"CLIENT", "Opdrachtgever"},
                {"OPPOSING", "Wederpartij"},
                {"PARTY", "Partij"},
                {"OPPONENT_COUNSIL", "Tegengestelde raadsman"},
        };
    }

}
