package com.ulegalize.international;

import java.util.ListResourceBundle;

/**
 * The type Message en.
 */
public class Message_en extends ListResourceBundle {

    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"VIREMENT", "Bank transfer"},
                {"CREDIT", "Credit card"},
                {"CASH", "Cash"},
                {"BANCONTACT", "Debit card"},
                {"CHEQUE", "Check"},
                {"NA", "N/A"},
                {"SELL", "Sales invoice"},
                {"CREDIT", "Credit score"},
                {"TEMP", "Temporary invoice"},
                {"TEMP_NC", "Temporary credit score"},
                {"PRO_ACCOUNT", "Professioneel account"},
                {"ACCOUNT_TIERS", "Third-party account / CARPA"},
                {"PERM", "Permanent"},
                {"RECORD", "Task recording"},
                {"TASK", "Task"},
                {"RDV", "Appointment"},
                {"AUD", "Audience"},
                {"OTH", "Other"},
                {"BA", "BAJ"},
                {"DC", "Case"},
                {"DF", "Collaborative law"},
                {"MD", "Mediation"},
                {"AVOCAT", "Lawyer"},
                {"STAGIAIRE", "Trainee"},
                {"ASSISTANT", "Assistant"},
                {"SECRETAIRE_JURIDIQUE", "Judicial secretary"},
                {"COLLABORATEUR", "Collaborater"},
                {"MEDIATEUR", "Mediator"},
                {"LAWYER_ADVICE_CLIENT", "Client adviser"},
                {"LAWYER_OPPOSING", "Opposing party lawyer"},
                {"LITIGANT_OPPOSING", "Justiciable opposing party"},
                {"LAWYER_CLIENT", "Lawyer Client"},
                {"LAWFIRM", "Law firm"},
                {"LITIGANT_CLIENT", "Litigant client"},
                {"F", "Madam"},
                {"L", "Miss"},
                {"M", "Sir"},
                {"A", "Master"},
                {"CHANNEL", "Channel"},
                {"M_001", "with"},
                {"SORTIE", "Output"},
                {"ENTREE", "Entry"},
                {"INVITELITIGANTCONSEIL", "Invitation on your folder"},
                {"INVITECONSEIL", "Invitation to work on a folder"},
                {"MAILBLANKTEMPLATE", "Sharing your folder"},
                {"MAILSIGNDOCUMENT", "Document signature"},
                {"MAILFINISHSIGNOWNERCLIENTDOCUMENT", "Document signature"},
                {"MAILFINISHSIGNCLIENTDOCUMENT", "Document signature"},
                {"MAILATTACHDOCUMENTCASE", "Document attached"},
                {"MAILATTACHDOCUMENTCASEFROMPORTAL", "A file has been attached to the legal case"},
                {"MAILSAVEOWNERCASE", "Change of coverage for the legal case"},
                {"MAILUPDATEDOCUMENTCASE", "Modification of the legal case"},
                {"MAILFINISHSIGNDOCUMENT", "Document signature"},
                {"MAILAPPOINTMENT_ADDED_NOTIFICATION", "Ulegalize: Notification agenda"},
                {"MAILAPPOINTMENT_CANCEL_NOTIFICATION", "Ulegalize: Cancel agenda"},
                {"MAILAPPOINTMENTCONFIRMEDTEMPLATE", "Ulegalize: Appointment request confirmed"},
                {"MAILAPPOINTMENTREGISTEREDTEMPLATE", "New appointment request"},
                {"MAILNEWAPPOINTMENTREQUESTTEMPLATE", "Appointment request recorded"},
                {"MAILSHAREDFOLDERUSERTEMPLATE", "New folder sharing"},
                {"MAILSHAREDUSERSECURITYTEMPLATE", "New access to the practice"},
                {"MAILVERIFYTEMPLATE", "Verify your user email"},
                {"MAILAUTOMATICREGISTER", "Welcome to the Workspace"},
                {"MAILAUTOMATICSUPPORT", "Support to the Workspace"},
                {"MAILAUTOMATICREMINDER", "Reminder support to the Workspace"},
                {"MAILWORKSPACEASSOCIATION", "Application for association with the lawfirm"},
                {"MAILPAYMENTCANCELTEMPLATE", "Cancellation of payment modules "},
                {"MAILPAYMENTFAILURETEMPLATE", "Error with payment method"},
                {"MAILREPORTKPI", "Report KPI"},
                {"MAILPOSTBID", "status of your shipment"},
                {"ADMINISTRATEUR", "Administrator"},
                {"TIERS_LECTURE", "Third Party - Read"},
                {"DOSSIERS_LECTURE", "Folders - Reading"},
                {"COMPTABILITE_LECTURE", "Accounting - Reading"},
                {"ECHEANCIER_LECTURE", "Schedule - Reading"},
                {"COMPTABILITE_IMPRESSIONDERAPPORTS", "Accounting - printing reports"},
                {"DOSSIERS_VOIRASPECTSFINANCIERS", "Records - see financial aspects"},
                {"DOSSIERS_VOIRNOTEAVOCAT", "Files - see note for counsel"},
                {"COMPTABILITE_ECRITURE", "Accounting - Writing"},
                {"DOSSIERS_FINANCIER", "Records - Financial"},
                {"TIMESHEET_ECRITURE", "Timesheet - writing"},
                {"DOSSIERS_DOCUMENTS", "Records - Documents"},
                {"DOSSIERS_ECRITURE", "Records - Writing"},
                {"TIERS_ECRITURE", "Third Party - Writing"},
                {"TABLEAUDEBORD", "Dashboard"},
                {"ECHEANCIER_ECRITURE", "Schedule - Writing"},
                {"TIMESHEET_LECTURE", "Timesheet - Reading"},
                {"FACTURE_LECTURE", "Invoice - Reading"},
                {"FACTURE_ECRITURE", "Invoice - Writing"},
                {"FACTURE_VALIDATION", "Invoice - Validation"},
                {"FACTURE_CONFIGURATION", "Invoice - Configuration"},
                {"AVODRIVE_LECTURE", "UDrive - Reading"},
                {"AVODRIVE_ECRITURE", "UDrive - Writing"},
                {"AVODRIVE_PARTAGE", "UDrive - Share"},
                {"GESTION_DU_COURIER_ENTRANT", "Incoming Courier Management"},
                {"CALENDAR_LECTURE", "Calendar - Reading"},
                {"CALENDAR_ECRITURE", "Calendar - Writing"},
                {"JUSTICIABLE_ECRITURE", "Litigant - Writing"},
                {"JUSTICIABLE_ADMIN", "Litigant - Admin"},
                {"SUPER_ADMIN", "Super - Admin"},
                // Template
                {"MAILTEMPLATEDOSSIER", "Your document is ready to be edited"},
                // EnumDossierContactType
                {"CLIENT", "Client"},
                {"OPPOSING", "Opposing party"},
                {"PARTY", "Party"},
                {"OPPONENT_COUNSIL", "Opposing counsil"},
                {"OTHER", "Other"},
        };
    }

}
